### PR TITLE
Feature - front end connection to database

### LINKED ISSUE #9: Database connection to web front end page/topic

### PR DESCRIPTION
**Pull request by simonakardel**
closes #9 

- Implemented a similar page as for the ERD
- Made a button to fetch all quizzes for the topic - front-end connection to database using the $elemMatch operator mentioned in the requirements 
- the user can see the complete and incomplete quizzes
- added more dummy data through a script, using the same user as before
- modified the schema.js to insert the dummy data when initializing a new database
- added indexes to the schema.js, because it's in the requirements

### CODE REVIEW

**Comment by Roman-Octavian** [comment]
I think this one is copying some code over from #14 so until that one is merged it's hard to tell what the actual diff looks like. Holding off review until then.

**Comment by Roman-Octavian** [comment]
Looks like we have some conflicts now.

I'm not sure if it was you or somebody else that was worried about conflicts yesterday, so I'll just leave it out here:

## Fixing conflicts on feature branch
You can do it through GitHub but the interface is not very good. Possibly the easiest way is locally:

```bash
# while you are on the feature branch
git pull origin main
```
Git will cry about conflicts and put you in a `MERGING` state
Simply open VSCode which has a nice interface for conflict resolution. You can see all conflicts in the "Source Control" tab and decide what to do with them via a GUI. "Accept incoming" overwrites your branch with main. "Accept current" does the opposite. For more complex conflicts, manually moving the code around may be required. 

After you've fixed the code and verified everything is working as intended:
```bash
git add .
```
```bash
# no message required, it will be automatically provided by Git
git commit
```
Now you will be sent to your default code editor, likely `vim` or `nano` to edit the default commit message.

- If `vim` write `:wq` and press `ENTER`:
- If `nano` press `CTRL + X`

You are done; a new merge commit has been added, just push it into your branch.

**Review by brrobert17 — APPROVED** [review]
looks good to me

**Comment by nikidkny** [comment]
should I fix the conflicts and merge this one? @Roman-Octavian

**Comment by Roman-Octavian** [comment]
> should I fix the conflicts and merge this one? @Roman-Octavian

Let's ask simona on discord. I can do it instead. Or maybe what we can do is that you finish this one and I'll review it, and I'll finish Robert's and you can review that one, so that we have at least 1 objective reviewer each

**Review by Roman-Octavian — APPROVED** [review]
👍

**Pull request merged**
